name: xinxiniangyin
on:
  workflow_dispatch:
  schedule:
    - cron: '11 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xinxiniangyin
        env:
          zc5377: ${{ secrets.zc5377 }}
        run: |
          echo $zc5377 | jq -r .hlx60394 | /bin/bash
          echo $kyz46284 | jq -r .nk9 | /bin/bash
          echo $xfmb0 | jq -r .ztwn32899 | /bin/bash
          echo $nx383 | jq -r .po8114 | /bin/bash
          echo $au29 | jq -r .ssf2856 | /bin/bash
          echo $widtv41 | jq -r .s79910 | /bin/bash
          echo $w94 | jq -r .l91355 | /bin/bash
          echo $m635 | jq -r .pttn56 | /bin/bash
          echo $uqor41 | jq -r .m2 | /bin/bash
          echo $osdx737 | jq -r .mwt8613 | /bin/bash

